environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONFIG: Release
      RID: win-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CONFIG: ReleaseLinux
      RID: linux-x64

platform: Any CPU
configuration: $(CONFIG)

before_build:
  - dotnet restore AmbermoonTools/AmbermoonTools.sln --verbosity normal

build:
  parallel: true
  project: AmbermoonTools/AmbermoonTools.sln

artifacts:
  - path: AmbermoonTools-Windows.zip
    name: AmbermoonTools-Windows
  - path: AmbermoonTools-Linux.tar.gz
    name: AmbermoonTools-Linux

after_build:
  - ps: dotnet publish -c $env:CONFIG "./AmbermoonTools/AmbermoonPack/AmbermoonPack.csproj" -p:PublishSingleFile=true -r $env:RID --no-restore
  - ps: dotnet publish -c $env:CONFIG "./AmbermoonTools/MonsterValueChanger/MonsterValueChanger.csproj" -p:PublishSingleFile=true -r $env:RID --no-restore
  - ps: dotnet publish -c $env:CONFIG "./AmbermoonTools/AmbermoonTextImport/AmbermoonTextImport.csproj" -p:PublishSingleFile=true -r $env:RID --no-restore
  - ps: ./AmbermoonTools/pack.ps1

test: off

deploy:
  - provider: GitHub
    name: AmbermoonTools-Windows
    artifact: AmbermoonTools-Windows
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmbermoonTools-Linux
    artifact: AmbermoonTools-Linux
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
