image: Visual Studio 2019

platform: Any CPU
configuration: Release

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

before_build:
  - dotnet restore AmbermoonTools/AmbermoonTools.sln --verbosity normal

build:
  project: AmbermoonTools/AmbermoonTools.sln

artifacts:
  - path: AmbermoonTools-Windows.zip
    name: AmbermoonTools-Windows

after_build:
  - 7z a AmbermoonTools-Windows.zip "%APPVEYOR_BUILD_FOLDER%\AmbermoonTools\Ambermoon.Common\bin\Release\netstandard2.1\Ambermoon.Common.dll"
  - 7z a AmbermoonTools-Windows.zip "%APPVEYOR_BUILD_FOLDER%\AmbermoonTools\Ambermoon.Data.Common\bin\Release\netstandard2.1\Ambermoon.Data.Common.dll"
  - 7z a AmbermoonTools-Windows.zip "%APPVEYOR_BUILD_FOLDER%\AmbermoonTools\Ambermoon.Data.Legacy\bin\Release\netstandard2.1\Ambermoon.Data.Legacy.dll"

test: off

deploy:
  - provider: GitHub
    name: AmbermoonTools-Windows
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    api_key:
      secure: UwVH6GHdh4zr7mDxC/HWXBQni/uzh36MV5lsXRmrgyyYEXJ67H63sI31QG4AByXY
    skip_symbols: true
    artifact: /.*(\.|\.s)nupkg/
    on:
      APPVEYOR_REPO_TAG: true
